[package]
name = "roll"
version = "0.1.0"
authors = ["Drew Mitchell <hi@callmedrew.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
regex = "1"
rand = "0.5.5"